name: Report Specific Filter Issue From Popup Panel
description: |
  DO NOT manually choose THIS TEMPLATE TO REPORT ISSUES.
  It's to be used by uBO version 1.38.7 and above through the new "Report" feature.
body:
  - type: checkboxes
    attributes:
      label: I tried to reproduce the issue when...
      description: |
        Perform these steps first to help unburden filter lists maintainers.
      options:
        - label: uBO is the only content blocker
          required: true
        - label: uBO with default settings/lists
          required: true

  - type: textarea
    attributes:
      label: URL address of the web page
      description: |
        Filled by uBO, leave it alone.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Category
      description: |
        Filled by uBO, leave it alone.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the issue
      description: |
        Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshot(s)
      description: |
        Screenshot(s) for **difficult to describe visual issues are mandatory**. 
        Post **links** instead of inline images for screenshots containing **adult material**.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Configuration
      description: |
        Filled by uBO, leave it alone.
    validations:
      required: true  
