name: GitHub CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '43 */8 * * *'

jobs:
  publish:
    name: Publish lists
    runs-on: ubuntu-latest
    steps:
      - name: Clone uAssets
        uses: actions/checkout@v3
        with:
            ref: gh-pages
      - name: Copy filter lists to gh-pages
        run: |
          TMPDIR=$(mktemp -d)
          git clone --depth=1 https://github.com/uBlockOrigin/uAssets.git $TMPDIR
          cp $TMPDIR/filters/*.txt filters/
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit changes (if any)
        run: |
          if [[ -n $(git diff) ]]; then
            git add -u filters/
            git commit -m "Update all filter lists"
            git push origin gh-pages
          fi
